controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: '/'
    controller: 'App\Controller\HomeController::index'

app_user:
    path: /benutzer
    controller: 'App\Controller\UserController::index'

create_user:
    path: /benutzer/erstellen
    controller: 'App\Controller\UserController::createUser'

user_totp:
    path: /benutzer/totp-generator
    controller: 'App\Controller\UserController::generateTotpSecret'

user_totp_setup:
    path: /benutzer/totp-setup
    controller: 'App\Controller\UserController::totpSetup'

user_totp_verify:
    path: /benutzer/totp-verify
    controller: 'App\Controller\UserController::verifyTotpCode'

disable_totp:
    path: /benutzer/deaktiviere-totp
    controller: 'App\Controller\UserController::disableTotp'

toggle_email_verification:
    path: /benutzer/toggle-email-verification
    controller: 'App\Controller\UserController::toggleEmailVerification'

app_settings:
    path: /einstellungen
    controller: 'App\Controller\SettingsController::index'

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout: 
    path: /logout
    controller: App\Controller\SecurityController::logout

dokumentation:
    path: /kundendoku
    controller: 'App\Controller\CustomerController::index'

zeiterfassung:
    path: /zeiterfassung
    controller: 'App\Controller\TimeTrackingController::index'

ajax_edit_generalinfo:
    path: /ajax/generalinfo/{id}
    controller: 'App\Controller\GeneralInfoController::ajaxEdit'

customer_create:
    path: /create
    controller: 'App\Controller\CustomerController::create'

customer_list:
    path: /api/kunden/suche
    controller: 'App\Controller\CustomerController::list'

is_confirmed:
    path: /is_confirmed
    controller: 'App\Controller\SecurityController::isConfirmed'
